version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies 
          command: ./setup-debian.sh;
      - run:
          name: Build without TUF
          command: echo "2" | ./build.sh;

